# Generated by Django 3.0.5 on 2021-06-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type_pizza', models.CharField(choices=[('regular', 'REGULAR'), ('square', 'SQUARE'), ('pie', 'PIE')], default='regular', max_length=20, verbose_name='Type Of Pizza')),
                ('size_pizza', models.CharField(max_length=120, verbose_name='Size Of Pizza')),
                ('topping_pizza', models.CharField(max_length=120, verbose_name='Topping For Pizza')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pizza',
                'verbose_name_plural': 'Pizzas',
            },
        ),
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'PizzaSize',
                'verbose_name_plural': 'PizzaSizes',
            },
        ),
        migrations.CreateModel(
            name='PizzaTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'PizzaTopping',
                'verbose_name_plural': 'PizzaToppings',
            },
        ),
    ]
