# Generated by Django 3.2.4 on 2021-06-20 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type_pizza', models.CharField(choices=[('regular', 'REGULAR'), ('square', 'SQUARE'), ('pie', 'PIE')], default='regular', max_length=20, verbose_name='Type Of Pizza')),
                ('description', models.TextField(blank=True, null=True)),
                ('size_pize', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pizza', to='core.pizzasize', verbose_name='Size Of Pizza')),
                ('topping_pize', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pizza', to='core.pizzatopping', verbose_name='Topping For Pizza')),
            ],
            options={
                'verbose_name': 'Pizza',
                'verbose_name_plural': 'Pizzas',
            },
        ),
    ]
