# Generated by Django 3.2.4 on 2021-06-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pizza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='size_pize',
            new_name='size_pizza',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='topping_pize',
            new_name='topping_pizza',
        ),
    ]
